/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdministracaoRouteImport } from './routes/_authenticated/administracao'
import { Route as AuthenticatedAnotadorRouteImport } from './routes/_authenticated/anotador'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedComercialRouteImport } from './routes/_authenticated/comercial'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedDiretoriasRouteImport } from './routes/_authenticated/diretorias'
import { Route as AuthenticatedDisponibilidadeRouteImport } from './routes/_authenticated/disponibilidade'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEfetivoRouteImport } from './routes/_authenticated/efetivo'
import { Route as AuthenticatedEscalaRouteImport } from './routes/_authenticated/escala'
import { Route as AuthenticatedEstrelariosRouteImport } from './routes/_authenticated/estrelarios'
import { Route as AuthenticatedFuncoesRouteImport } from './routes/_authenticated/funcoes'
import { Route as AuthenticatedGaivotometroRouteImport } from './routes/_authenticated/gaivotometro'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedMaterialCargaRouteImport } from './routes/_authenticated/material-carga'
import { Route as AuthenticatedMeteorologiaRouteImport } from './routes/_authenticated/meteorologia'
import { Route as AuthenticatedPanoramaRouteImport } from './routes/_authenticated/panorama'
import { Route as AuthenticatedPitocadorRouteImport } from './routes/_authenticated/pitocador'
import { Route as AuthenticatedQuadroRouteImport } from './routes/_authenticated/quadro'
import { Route as AuthenticatedSegurancaRouteImport } from './routes/_authenticated/seguranca'
import { Route as AuthenticatedSupervisaoRouteImport } from './routes/_authenticated/supervisao'
import { Route as AuthenticatedDiretoriaIdRouteImport } from './routes/_authenticated/diretoria.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministracaoRoute =
  AuthenticatedAdministracaoRouteImport.update({
    id: '/administracao',
    path: '/administracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnotadorRoute = AuthenticatedAnotadorRouteImport.update({
  id: '/anotador',
  path: '/anotador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComercialRoute = AuthenticatedComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiretoriasRoute = AuthenticatedDiretoriasRouteImport.update({
  id: '/diretorias',
  path: '/diretorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisponibilidadeRoute =
  AuthenticatedDisponibilidadeRouteImport.update({
    id: '/disponibilidade',
    path: '/disponibilidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEfetivoRoute = AuthenticatedEfetivoRouteImport.update({
  id: '/efetivo',
  path: '/efetivo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscalaRoute = AuthenticatedEscalaRouteImport.update({
  id: '/escala',
  path: '/escala',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstrelariosRoute =
  AuthenticatedEstrelariosRouteImport.update({
    id: '/estrelarios',
    path: '/estrelarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFuncoesRoute = AuthenticatedFuncoesRouteImport.update({
  id: '/funcoes',
  path: '/funcoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGaivotometroRoute =
  AuthenticatedGaivotometroRouteImport.update({
    id: '/gaivotometro',
    path: '/gaivotometro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialCargaRoute =
  AuthenticatedMaterialCargaRouteImport.update({
    id: '/material-carga',
    path: '/material-carga',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeteorologiaRoute =
  AuthenticatedMeteorologiaRouteImport.update({
    id: '/meteorologia',
    path: '/meteorologia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanoramaRoute = AuthenticatedPanoramaRouteImport.update({
  id: '/panorama',
  path: '/panorama',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPitocadorRoute = AuthenticatedPitocadorRouteImport.update({
  id: '/pitocador',
  path: '/pitocador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuadroRoute = AuthenticatedQuadroRouteImport.update({
  id: '/quadro',
  path: '/quadro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSegurancaRoute = AuthenticatedSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisaoRoute = AuthenticatedSupervisaoRouteImport.update({
  id: '/supervisao',
  path: '/supervisao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiretoriaIdRoute =
  AuthenticatedDiretoriaIdRouteImport.update({
    id: '/diretoria/$id',
    path: '/diretoria/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/anotador': typeof AuthenticatedAnotadorRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/conta': typeof AuthenticatedContaRoute
  '/diretorias': typeof AuthenticatedDiretoriasRoute
  '/disponibilidade': typeof AuthenticatedDisponibilidadeRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/efetivo': typeof AuthenticatedEfetivoRoute
  '/escala': typeof AuthenticatedEscalaRoute
  '/estrelarios': typeof AuthenticatedEstrelariosRoute
  '/funcoes': typeof AuthenticatedFuncoesRoute
  '/gaivotometro': typeof AuthenticatedGaivotometroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/material-carga': typeof AuthenticatedMaterialCargaRoute
  '/meteorologia': typeof AuthenticatedMeteorologiaRoute
  '/panorama': typeof AuthenticatedPanoramaRoute
  '/pitocador': typeof AuthenticatedPitocadorRoute
  '/quadro': typeof AuthenticatedQuadroRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/supervisao': typeof AuthenticatedSupervisaoRoute
  '/diretoria/$id': typeof AuthenticatedDiretoriaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/anotador': typeof AuthenticatedAnotadorRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/conta': typeof AuthenticatedContaRoute
  '/diretorias': typeof AuthenticatedDiretoriasRoute
  '/disponibilidade': typeof AuthenticatedDisponibilidadeRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/efetivo': typeof AuthenticatedEfetivoRoute
  '/escala': typeof AuthenticatedEscalaRoute
  '/estrelarios': typeof AuthenticatedEstrelariosRoute
  '/funcoes': typeof AuthenticatedFuncoesRoute
  '/gaivotometro': typeof AuthenticatedGaivotometroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/home': typeof AuthenticatedHomeRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/material-carga': typeof AuthenticatedMaterialCargaRoute
  '/meteorologia': typeof AuthenticatedMeteorologiaRoute
  '/panorama': typeof AuthenticatedPanoramaRoute
  '/pitocador': typeof AuthenticatedPitocadorRoute
  '/quadro': typeof AuthenticatedQuadroRoute
  '/seguranca': typeof AuthenticatedSegurancaRoute
  '/supervisao': typeof AuthenticatedSupervisaoRoute
  '/diretoria/$id': typeof AuthenticatedDiretoriaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/administracao': typeof AuthenticatedAdministracaoRoute
  '/_authenticated/anotador': typeof AuthenticatedAnotadorRoute
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/comercial': typeof AuthenticatedComercialRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/diretorias': typeof AuthenticatedDiretoriasRoute
  '/_authenticated/disponibilidade': typeof AuthenticatedDisponibilidadeRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/efetivo': typeof AuthenticatedEfetivoRoute
  '/_authenticated/escala': typeof AuthenticatedEscalaRoute
  '/_authenticated/estrelarios': typeof AuthenticatedEstrelariosRoute
  '/_authenticated/funcoes': typeof AuthenticatedFuncoesRoute
  '/_authenticated/gaivotometro': typeof AuthenticatedGaivotometroRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/material-carga': typeof AuthenticatedMaterialCargaRoute
  '/_authenticated/meteorologia': typeof AuthenticatedMeteorologiaRoute
  '/_authenticated/panorama': typeof AuthenticatedPanoramaRoute
  '/_authenticated/pitocador': typeof AuthenticatedPitocadorRoute
  '/_authenticated/quadro': typeof AuthenticatedQuadroRoute
  '/_authenticated/seguranca': typeof AuthenticatedSegurancaRoute
  '/_authenticated/supervisao': typeof AuthenticatedSupervisaoRoute
  '/_authenticated/diretoria/$id': typeof AuthenticatedDiretoriaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/administracao'
    | '/anotador'
    | '/avisos'
    | '/calendario'
    | '/comercial'
    | '/conta'
    | '/diretorias'
    | '/disponibilidade'
    | '/documentos'
    | '/efetivo'
    | '/escala'
    | '/estrelarios'
    | '/funcoes'
    | '/gaivotometro'
    | '/historico'
    | '/home'
    | '/logs'
    | '/material-carga'
    | '/meteorologia'
    | '/panorama'
    | '/pitocador'
    | '/quadro'
    | '/seguranca'
    | '/supervisao'
    | '/diretoria/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/administracao'
    | '/anotador'
    | '/avisos'
    | '/calendario'
    | '/comercial'
    | '/conta'
    | '/diretorias'
    | '/disponibilidade'
    | '/documentos'
    | '/efetivo'
    | '/escala'
    | '/estrelarios'
    | '/funcoes'
    | '/gaivotometro'
    | '/historico'
    | '/home'
    | '/logs'
    | '/material-carga'
    | '/meteorologia'
    | '/panorama'
    | '/pitocador'
    | '/quadro'
    | '/seguranca'
    | '/supervisao'
    | '/diretoria/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/administracao'
    | '/_authenticated/anotador'
    | '/_authenticated/avisos'
    | '/_authenticated/calendario'
    | '/_authenticated/comercial'
    | '/_authenticated/conta'
    | '/_authenticated/diretorias'
    | '/_authenticated/disponibilidade'
    | '/_authenticated/documentos'
    | '/_authenticated/efetivo'
    | '/_authenticated/escala'
    | '/_authenticated/estrelarios'
    | '/_authenticated/funcoes'
    | '/_authenticated/gaivotometro'
    | '/_authenticated/historico'
    | '/_authenticated/home'
    | '/_authenticated/logs'
    | '/_authenticated/material-carga'
    | '/_authenticated/meteorologia'
    | '/_authenticated/panorama'
    | '/_authenticated/pitocador'
    | '/_authenticated/quadro'
    | '/_authenticated/seguranca'
    | '/_authenticated/supervisao'
    | '/_authenticated/diretoria/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administracao': {
      id: '/_authenticated/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AuthenticatedAdministracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anotador': {
      id: '/_authenticated/anotador'
      path: '/anotador'
      fullPath: '/anotador'
      preLoaderRoute: typeof AuthenticatedAnotadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial': {
      id: '/_authenticated/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AuthenticatedComercialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diretorias': {
      id: '/_authenticated/diretorias'
      path: '/diretorias'
      fullPath: '/diretorias'
      preLoaderRoute: typeof AuthenticatedDiretoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disponibilidade': {
      id: '/_authenticated/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/disponibilidade'
      preLoaderRoute: typeof AuthenticatedDisponibilidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/efetivo': {
      id: '/_authenticated/efetivo'
      path: '/efetivo'
      fullPath: '/efetivo'
      preLoaderRoute: typeof AuthenticatedEfetivoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escala': {
      id: '/_authenticated/escala'
      path: '/escala'
      fullPath: '/escala'
      preLoaderRoute: typeof AuthenticatedEscalaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estrelarios': {
      id: '/_authenticated/estrelarios'
      path: '/estrelarios'
      fullPath: '/estrelarios'
      preLoaderRoute: typeof AuthenticatedEstrelariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcoes': {
      id: '/_authenticated/funcoes'
      path: '/funcoes'
      fullPath: '/funcoes'
      preLoaderRoute: typeof AuthenticatedFuncoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gaivotometro': {
      id: '/_authenticated/gaivotometro'
      path: '/gaivotometro'
      fullPath: '/gaivotometro'
      preLoaderRoute: typeof AuthenticatedGaivotometroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/material-carga': {
      id: '/_authenticated/material-carga'
      path: '/material-carga'
      fullPath: '/material-carga'
      preLoaderRoute: typeof AuthenticatedMaterialCargaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meteorologia': {
      id: '/_authenticated/meteorologia'
      path: '/meteorologia'
      fullPath: '/meteorologia'
      preLoaderRoute: typeof AuthenticatedMeteorologiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panorama': {
      id: '/_authenticated/panorama'
      path: '/panorama'
      fullPath: '/panorama'
      preLoaderRoute: typeof AuthenticatedPanoramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pitocador': {
      id: '/_authenticated/pitocador'
      path: '/pitocador'
      fullPath: '/pitocador'
      preLoaderRoute: typeof AuthenticatedPitocadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quadro': {
      id: '/_authenticated/quadro'
      path: '/quadro'
      fullPath: '/quadro'
      preLoaderRoute: typeof AuthenticatedQuadroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seguranca': {
      id: '/_authenticated/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof AuthenticatedSegurancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervisao': {
      id: '/_authenticated/supervisao'
      path: '/supervisao'
      fullPath: '/supervisao'
      preLoaderRoute: typeof AuthenticatedSupervisaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diretoria/$id': {
      id: '/_authenticated/diretoria/$id'
      path: '/diretoria/$id'
      fullPath: '/diretoria/$id'
      preLoaderRoute: typeof AuthenticatedDiretoriaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministracaoRoute: typeof AuthenticatedAdministracaoRoute
  AuthenticatedAnotadorRoute: typeof AuthenticatedAnotadorRoute
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedComercialRoute: typeof AuthenticatedComercialRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedDiretoriasRoute: typeof AuthenticatedDiretoriasRoute
  AuthenticatedDisponibilidadeRoute: typeof AuthenticatedDisponibilidadeRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEfetivoRoute: typeof AuthenticatedEfetivoRoute
  AuthenticatedEscalaRoute: typeof AuthenticatedEscalaRoute
  AuthenticatedEstrelariosRoute: typeof AuthenticatedEstrelariosRoute
  AuthenticatedFuncoesRoute: typeof AuthenticatedFuncoesRoute
  AuthenticatedGaivotometroRoute: typeof AuthenticatedGaivotometroRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMaterialCargaRoute: typeof AuthenticatedMaterialCargaRoute
  AuthenticatedMeteorologiaRoute: typeof AuthenticatedMeteorologiaRoute
  AuthenticatedPanoramaRoute: typeof AuthenticatedPanoramaRoute
  AuthenticatedPitocadorRoute: typeof AuthenticatedPitocadorRoute
  AuthenticatedQuadroRoute: typeof AuthenticatedQuadroRoute
  AuthenticatedSegurancaRoute: typeof AuthenticatedSegurancaRoute
  AuthenticatedSupervisaoRoute: typeof AuthenticatedSupervisaoRoute
  AuthenticatedDiretoriaIdRoute: typeof AuthenticatedDiretoriaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministracaoRoute: AuthenticatedAdministracaoRoute,
  AuthenticatedAnotadorRoute: AuthenticatedAnotadorRoute,
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedComercialRoute: AuthenticatedComercialRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedDiretoriasRoute: AuthenticatedDiretoriasRoute,
  AuthenticatedDisponibilidadeRoute: AuthenticatedDisponibilidadeRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEfetivoRoute: AuthenticatedEfetivoRoute,
  AuthenticatedEscalaRoute: AuthenticatedEscalaRoute,
  AuthenticatedEstrelariosRoute: AuthenticatedEstrelariosRoute,
  AuthenticatedFuncoesRoute: AuthenticatedFuncoesRoute,
  AuthenticatedGaivotometroRoute: AuthenticatedGaivotometroRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMaterialCargaRoute: AuthenticatedMaterialCargaRoute,
  AuthenticatedMeteorologiaRoute: AuthenticatedMeteorologiaRoute,
  AuthenticatedPanoramaRoute: AuthenticatedPanoramaRoute,
  AuthenticatedPitocadorRoute: AuthenticatedPitocadorRoute,
  AuthenticatedQuadroRoute: AuthenticatedQuadroRoute,
  AuthenticatedSegurancaRoute: AuthenticatedSegurancaRoute,
  AuthenticatedSupervisaoRoute: AuthenticatedSupervisaoRoute,
  AuthenticatedDiretoriaIdRoute: AuthenticatedDiretoriaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
